### ISSUE TITLE
The effectiveness of  “Coarse-to-Fine Framework”

### ISSUE THREAD

**Issue by wangpengbo31348** [Show-han/PET-Reconstruction#5]
Cloud you please confirm if your model has undergone ablation experiments on the effectiveness of your “Coarse-to-Fine Framework”？ I have observed that whether using your own medical data or the GoPro deblurring dataset used in your baseline “ Deblurring via Stochastic Refinement”, the performance metrics are poor when “ Auxiliary Guidance Strategy” and “Contrastive Diffusion Strategy” are excluded. It could even be said that there is virtually no effect.

**Comment by wyhlovecpp** [comment]
Thanks for your question. The ablation experiments don't have any mistakes. We first changed this baseline "dvsr" based on SR3, which only needed a little modification. And verified the results of this model many times.

Based on my experimental experience, I think your problem is mainly with the residual network prediction. The results of residual prediction often get all zero tensor or abnormal value. I asked the author of "dvsr", and this is a very common question. Due to its inherent two-stage network, the training process is not stable. It requires careful design of hyperparameters and the unet model. In our medical dataset, we have try different parameters and find that the best effect is to try to keep the parameters of the two networks at 25m vs 6m, which is similar to the parameters of "dvsr". All ablation experiments were performed under same config in our github code. 

For GoPro deblurring dataset, I don't know much about it. Because the model design of our unet is also different from "dvsr". The "dvsr", which removes the middle layer attention and the special design in sr3, will get very poor results on our medical dataset. So if you want to test on GoPro, refer to "dvsr" for details.
